services:
  memgraph:
    image: memgraph/memgraph-platform:latest
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
      - "3000:3000"
    environment:
      - MEMGRAPH_ENABLE_CYPHER=true
      # - MEMGRAPH_ENABLE_PROMETHEUS=true
    volumes:
      - memgraph_data:/var/lib/memgraph

volumes:
  memgraph_data:
    driver: local